package com.weberbox.pifire.enums;

public enum OneSignalResult {
    ONESIGNAL_NO_ID,
    ONESIGNAL_NO_CONSENT,
    ONESIGNAL_NOT_REGISTERED,
    ONESIGNAL_APP_UPDATED,
    ONESIGNAL_DEVICE_ERROR,
    ONESIGNAL_NULL_TOKEN,
    ONESIGNAL_REGISTERED,
    ONESIGNAL_NOT_SUBSCRIBED
}
